<script>
 import {onMount} from 'svelte';import {supabase,employeeAction} from './supabase';import Selector from './Selector.svelte';import JobSeekers from './JobSeekers.svelte';
 export let table;export let id;export let back;export let saved;export let canEditEmployees=true;
 let original=null,form={},editing=id==='new',busy=false,loading=id!=='new',error='',createUser=false,loginEmail='',password='',manager=false;
 const fields={Jobs:[['Title','Title']],Companies:[['nameCompany','Company Name']],People:[['nameFirst','First Name'],['nameLast','Last Name']],Employees:[['nameFirst','First Name'],['nameLast','Last Name'],['email','Email']],Industries:[['nameIndustry','Name']],Skills:[['nameSkill','Name']],Licenses:[['nameLicense','Name']],Education:[['nameEducation','Name']]};
 const singular={Jobs:'Job',Companies:'Company',People:'Person',Employees:'Employee',Industries:'Industry',Skills:'Skill',Licenses:'License',Education:'Education'};
 onMount(async()=>{if(id==='new'){form=table==='Jobs'?{Status:'Pending',id_Company:''}:table==='Companies'?{flag_Client:false}:table==='People'?{flag_Seeker:false}:table==='Employees'?{flag_Manager:false}:{};return;}const r=await supabase.from(table).select('*').eq('id',id).single();error=r.error?.message||'';original=r.data;form={...original};loading=false;});
 $: passwordValid=password.length>=12&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/[0-9]/.test(password)&&/[^A-Za-z0-9]/.test(password);
 function cancel(){if(id==='new')back();else{form={...original};editing=false;error='';}}
 async function save(){busy=true;error='';try{let data;if(table==='Employees'){data=await employeeAction('save',{...(id==='new'?{}:{id}),...form});}else{const values={};for(const [key]of fields[table])values[key]=String(form[key]||'').trim();if(table==='Jobs'){values.id_Company=form.id_Company;values.Status='Pending';}if(table==='Companies')values.flag_Client=form.flag_Client===true;if(table==='People')values.flag_Seeker=form.flag_Seeker===true;const r=id==='new'?await supabase.from(table).insert(values).select().single():await supabase.from(table).update(values).eq('id',id).select().single();if(r.error)throw r.error;data=r.data;}original=data;form={...data};editing=false;if(id==='new')saved(data.id);}catch(e){error=e.message;}busy=false;}
 async function makeUser(){busy=true;error='';try{const data=await employeeAction('create-user',{id,email:loginEmail,password,flag_Manager:manager});original=data;form={...data};createUser=false;password='';}catch(e){error=e.message;}busy=false;}
</script>
<div class="toolbar"><div><button class="text" on:click={back}>← {table}</button><h1>{id==='new'?'New ':''}{singular[table]}{table==='Jobs'&&original?` #${original['seq']}`:''}</h1></div>{#if !editing&&!loading&&original&&(table!=='Employees'||canEditEmployees)}<button class="secondary" on:click={()=>{editing=true;createUser=false;}}>Edit</button>{/if}</div>
{#if error}<p role="alert" class="error">{error}</p>{/if}
{#if loading}<p>Loading…</p>{:else if id==='new'||original}
<form class="panel" on:submit|preventDefault={save}><div class="form-grid">
{#if table==='Jobs'}<label>seq<input readonly value={form['seq']||'Generated on Save'}/></label><label>Status<input readonly value="Pending"/></label>{/if}
{#each fields[table] as [key,label]}<label>{label}{#if editing&&key!=='email'} <span class="required">*</span>{/if}<input type={key==='email'?'email':'text'} bind:value={form[key]} readonly={!editing||busy} required={key!=='email'||!!form.id_User}/></label>{/each}
{#if table==='Jobs'}<label class="wide">Client {#if editing}<span class="required">*</span>{/if}<Selector table="Companies" flag="flag_Client" label="Clients" bind:value={form.id_Company} disabled={!editing||busy}/>{#if editing&&!form.id_Company}<small>Select a Company marked as a Client.</small>{/if}</label>{/if}
{#if table==='Companies'}<label class="check"><input type="checkbox" bind:checked={form.flag_Client} disabled={!editing||busy}/>Client</label>{/if}
{#if table==='People'}<label class="check"><input type="checkbox" bind:checked={form.flag_Seeker} disabled={!editing||busy}/>Seeker</label>{/if}
{#if table==='Employees'}<label class="check"><input type="checkbox" bind:checked={form.flag_Manager} disabled={!editing||busy||id==='new'}/>Manager</label>{#if id==='new'}<small>New Employees start without Manager access.</small>{/if}<label>User Account<input readonly value={form.id_User?'Linked':'No account'}/></label>{/if}
</div>{#if editing}<small>* Required fields</small><div class="actions"><button type="button" class="secondary" disabled={busy} on:click={cancel}>Cancel</button><button disabled={busy||(table==='Jobs'&&!form.id_Company)}>{busy?'Saving…':'Save'}</button></div>{/if}</form>
{#if table==='Jobs'&&id!=='new'&&!editing}<JobSeekers job={id}/>{/if}
{#if table==='Employees'&&id!=='new'&&!form.id_User&&!editing&&canEditEmployees}
{#if !createUser}<div class="actions"><button on:click={()=>{loginEmail=form.email||'';manager=form.flag_Manager;createUser=true;}}>Create User</button></div>{:else}<form class="panel" on:submit|preventDefault={makeUser}><h2>Create User</h2><div class="form-grid"><label>Login Email<input type="email" required bind:value={loginEmail}/></label><label>Temporary Password<input type="password" autocomplete="new-password" required bind:value={password}/></label><label class="check"><input type="checkbox" bind:checked={manager}/>Manager access</label></div><p class:valid={passwordValid}>Password requires at least 12 characters with an uppercase letter, lowercase letter, number and symbol.</p><div class="actions"><button type="button" class="secondary" disabled={busy} on:click={()=>{createUser=false;password='';}}>Cancel</button><button disabled={busy||!passwordValid||!loginEmail}>{busy?'Creating…':'Create User'}</button></div></form>{/if}
{/if}{/if}
