<script>
 import {onMount} from 'svelte';import {supabase} from './lib/supabase';import List from './lib/List.svelte';import Detail from './lib/Detail.svelte';import Home from './lib/Home.svelte';
 const logoUrl='https://agrecruit.com.au/assets/uploads/2026/02/agribusiness-recruitment-logo_horz_RGB.png';
 let session=null,employee=null,initializing=!!supabase,email='',password='',busy=false,error='',view='Home',record='',authVersion=0;
 function readUrl(){const params=new URLSearchParams(location.search);view=['Home','Jobs','Companies','People','Employees','Industries','Skills','Licenses','Education'].includes(params.get('view'))?params.get('view'):'Home';record=params.get('id')||'';}
 function navigate(v,id=''){const u=new URL(location.href);u.searchParams.set('view',v);if(id)u.searchParams.set('id',id);else u.searchParams.delete('id');history.pushState({},'',u);readUrl();error='';}
 async function applySession(next){const seq=++authVersion;session=next;employee=null;initializing=!!next;if(next){const r=await supabase.from('Employees').select('*').eq('id_User',next.user.id).single();if(seq!==authVersion)return;employee=r.data;error=r.error?'Your login has no accessible Employee record. Contact your administrator.':'';}initializing=false;}
 onMount(()=>{readUrl();window.addEventListener('popstate',readUrl);let sub;if(supabase){supabase.auth.getSession().then(({data})=>applySession(data.session));sub=supabase.auth.onAuthStateChange((_event,next)=>{setTimeout(()=>applySession(next),0);}).data.subscription;}return()=>{sub?.unsubscribe();window.removeEventListener('popstate',readUrl);authVersion++;};});
 async function login(){busy=true;error='';const r=await supabase.auth.signInWithPassword({email,password});if(r.error)error=r.error.message;password='';busy=false;}
 async function logout(){const r=await supabase.auth.signOut();if(r.error)error=r.error.message;}
 function accountLabel(e){return [e?.nameFirst,e?.nameLast].filter(Boolean).join(' ')||session?.user?.email;}
</script>
{#if !supabase}<main class="login"><div class="brand"><img src={logoUrl} alt="Agribusiness Recruitment"/></div><section class="panel"><h1>Connect your application</h1><p>Add your Supabase project URL and publishable key to <code>.env</code>, following the included README, then restart the application.</p></section></main>
{:else if initializing}<main class="login"><p>Loading your account…</p></main>
{:else if !session}<main class="login"><div class="brand"><img src={logoUrl} alt="Agribusiness Recruitment"/></div><form class="panel" on:submit|preventDefault={login}><h1>Sign in</h1>{#if error}<p class="error" role="alert">{error}</p>{/if}<label>Email<input type="email" autocomplete="username" required bind:value={email}/></label><label>Password<input type="password" autocomplete="current-password" required bind:value={password}/></label><div class="actions"><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></div></form></main>
{:else}<div class="shell"><aside><a class="brand" href="?view=Home" on:click|preventDefault={()=>navigate('Home')}><img src={logoUrl} alt="Agribusiness Recruitment"/></a><nav>{#each ['Jobs','Companies','People','Industries','Skills','Licenses','Education',...(employee?.flag_Manager?['Employees']:[])] as tab}<a class:active={view===tab} href={`?view=${tab}`} on:click|preventDefault={()=>navigate(tab)}>{tab}</a>{/each}</nav><div class="account">{#if employee}<button class="text" on:click={()=>navigate('Employees',employee.id)}>{accountLabel(employee)}</button>{:else}<span>{session.user.email}</span>{/if}<button class="text" on:click={logout}>Sign out</button></div></aside><main>
{#if !employee}<p class="error" role="alert">{error||'Employee access required.'}</p>{:else if view==='Employees'&&!employee.flag_Manager&&record!==employee.id}<h1>Manager access required</h1><p>Contact a Manager to access Employees.</p>{:else if view==='Home'}<Home {employee} {navigate}/>{:else}{#key `${view}:${record}`}{#if record}<Detail table={view} id={record} back={()=>navigate(view)} saved={id=>navigate(view,id)} canEditEmployees={employee.flag_Manager}/>{:else}<List table={view} open={id=>navigate(view,id)}/>{/if}{/key}{/if}
</main></div>{/if}
