<script>
 import {onMount} from 'svelte';import {supabase} from './lib/supabase';import List from './lib/List.svelte';import Detail from './lib/Detail.svelte';import Home from './lib/Home.svelte';import SettingsPage from './lib/Settings.svelte';
 const logoUrl='https://agrecruit.com.au/assets/uploads/2026/02/agribusiness-recruitment-logo_horz_RGB.png';
 const tableFor={Clients:'Companies',Seekers:'People'};
 const presetFilterFor={Clients:{key:'flag_Client',value:true},Seekers:{key:'flag_Seeker',value:true}};
 const settingsViews=['Industries','Skills','Licenses','Education','Statuses','Employees'];
 let session=null,employee=null,initializing=!!supabase,email='',password='',busy=false,error='',view='Home',record='',statusFilter='',statuses=[],authVersion=0;
 function readUrl(){const params=new URLSearchParams(location.search);view=['Home','Jobs','Companies','People','Employees','Industries','Skills','Licenses','Education','Statuses','Clients','Seekers','Settings'].includes(params.get('view'))?params.get('view'):'Home';record=params.get('id')||'';statusFilter=params.get('status')||'';}
 function navigate(v,id='',status=''){const leavingStatuses=view==='Statuses'&&v!=='Statuses';const u=new URL(location.href);u.searchParams.set('view',v);if(id)u.searchParams.set('id',id);else u.searchParams.delete('id');if(status)u.searchParams.set('status',status);else u.searchParams.delete('status');history.pushState({},'',u);readUrl();error='';if(leavingStatuses||v==='Jobs')loadStatuses();}
 async function loadStatuses(){const r=await supabase.from('Statuses').select('*').order('sort',{ascending:true,nullsFirst:false}).order('status');const list=r.data||[];const counts=await Promise.all(list.map(s=>supabase.from('Jobs').select('id',{count:'exact',head:true}).eq('id_Status',s.id)));statuses=list.map((s,i)=>({...s,jobCount:counts[i].count||0}));}
 async function applySession(next){const seq=++authVersion;session=next;employee=null;initializing=!!next;if(next){const r=await supabase.from('Employees').select('*').eq('id_User',next.user.id).single();if(seq!==authVersion)return;employee=r.data;error=r.error?'Your login has no accessible Employee record. Contact your administrator.':'';if(employee)loadStatuses();}initializing=false;}
 onMount(()=>{readUrl();window.addEventListener('popstate',readUrl);let sub;if(supabase){supabase.auth.getSession().then(({data})=>applySession(data.session));sub=supabase.auth.onAuthStateChange((_event,next)=>{setTimeout(()=>applySession(next),0);}).data.subscription;}return()=>{sub?.unsubscribe();window.removeEventListener('popstate',readUrl);authVersion++;};});
 async function login(){busy=true;error='';const r=await supabase.auth.signInWithPassword({email,password});if(r.error)error=r.error.message;password='';busy=false;}
 async function logout(){const r=await supabase.auth.signOut();if(r.error)error=r.error.message;}
 function accountLabel(e){return [e?.nameFirst,e?.nameLast].filter(Boolean).join(' ')||session?.user?.email;}
</script>
{#if !supabase}<main class="login"><div class="brand"><img src={logoUrl} alt="Agribusiness Recruitment"/></div><section class="panel"><h1>Connect your application</h1><p>Add your Supabase project URL and publishable key to <code>.env</code>, following the included README, then restart the application.</p></section></main>
{:else if initializing}<main class="login"><p>Loading your account…</p></main>
{:else if !session}<main class="login"><div class="brand"><img src={logoUrl} alt="Agribusiness Recruitment"/></div><form class="panel" on:submit|preventDefault={login}><h1>Sign in</h1>{#if error}<p class="error" role="alert">{error}</p>{/if}<label>Email<input type="email" autocomplete="username" required bind:value={email}/></label><label>Password<input type="password" autocomplete="current-password" required bind:value={password}/></label><div class="actions"><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></div></form></main>
{:else}<div class="shell"><aside><a class="brand" href="?view=Home" on:click|preventDefault={()=>navigate('Home')}><img src={logoUrl} alt="Agribusiness Recruitment"/></a><nav><div class="nav-section">Jobs</div>{#each statuses as s}<a class:active={view==='Jobs'&&statusFilter===s.id} href={`?view=Jobs&status=${s.id}`} on:click|preventDefault={()=>navigate('Jobs','',s.id)}>{s.status}{#if s.jobCount>0} <span class="nav-count">{s.jobCount}</span>{/if}</a>{/each}{#each ['Clients','Seekers','Settings'] as tab}<a class:active={tab==='Settings'?settingsViews.includes(view):view===tab} href={`?view=${tab}`} on:click|preventDefault={()=>navigate(tab)}>{tab}</a>{/each}</nav><div class="account">{#if employee}<button class="text" on:click={()=>navigate('Employees',employee.id)}>{accountLabel(employee)}</button>{:else}<span>{session.user.email}</span>{/if}<button class="text" on:click={logout}>Sign out</button></div></aside><main>
{#if !employee}<p class="error" role="alert">{error||'Employee access required.'}</p>{:else if view==='Employees'&&!employee.flag_Manager&&record!==employee.id}<h1>Manager access required</h1><p>Contact a Manager to access Employees.</p>{:else if view==='Home'}<Home {employee} {navigate} {statuses}/>{:else if view==='Settings'}<SettingsPage {employee} {navigate}/>{:else}{#key `${view}:${record}:${statusFilter}`}{#if record}<Detail table={tableFor[view]||view} id={record} back={()=>navigate(view,'',statusFilter)} saved={id=>navigate(view,id,statusFilter)} canEditEmployees={employee.flag_Manager} seekerMode={view==='Seekers'} clientMode={view==='Clients'} {navigate}/>{:else}<List table={tableFor[view]||view} heading={view==='Jobs'&&statusFilter?(statuses.find(s=>s.id===statusFilter)?.status||'Jobs'):view} presetFilter={view==='Jobs'&&statusFilter?{key:'id_Status',value:statusFilter}:(presetFilterFor[view]||null)} open={id=>navigate(view,id,statusFilter)}/>{/if}{/key}{/if}
</main></div>{/if}
